version: '2.2'

services:
    ubiquity-mint-live-monitor:
        stdin_open: true
        tty: true
        build:
            context: .
        env_file:
            - .env
        ports:
            - "3000:3000"