version: '2.2'

services:
    ubiquity-mint-live-monitor:
        stdin_open: true
        tty: true
        build:
            context: .
        environment:
        - API_KEY=${API_KEY}
        ports:
            - "3000:3000"